<?php
// Generated by Zend Framework 2
return array(
    'UthandoFileManager\Module'                           => __DIR__ . '/Module.php',
    'UthandoFileManager\Controller\FileManagerController' => __DIR__ . '/src/UthandoFileManager/Controller/FileManagerController.php',
    'UthandoFileManager\Controller\UploaderController'    => __DIR__ . '/src/UthandoFileManager/Controller/UploaderController.php',
    'UthandoFileManager\Form\Image'                       => __DIR__ . '/src/UthandoFileManager/Form/Image.php',
    'UthandoFileManager\Hydrator\Image'                   => __DIR__ . '/src/UthandoFileManager/Hydrator/Image.php',
    'UthandoFileManager\InputFilter\Image'                => __DIR__ . '/src/UthandoFileManager/InputFilter/Image.php',
    'UthandoFileManager\Model\Image'                      => __DIR__ . '/src/UthandoFileManager/model/Image.php',
    'UthandoFileManager\Option\FileManagerOptions'        => __DIR__ . '/src/UthandoFileManager/Option/FileManagerOptions.php',
    'UthandoFileManager\Service\ImageUploader'            => __DIR__ . '/src/UthandoFileManager/Service/ImageUploader.php',
    'UthandoFileManager\Service\Uploader'                 => __DIR__ . '/src/UthandoFileManager/Service/Uploader.php',
    'UthandoFileManager\UthandoFileManagerException'      => __DIR__ . '/src/UthandoFileManager/UthandoFileManagerException.php',
);