<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'UthandoFileManager\Module'                             => __DIR__ . '/Module.php',
    'UthandoFileManager\Controller\AssetManagerController'  => __DIR__ . '/src/UthandoFileManager/Controller/AssetManagerController.php',
    'UthandoFileManager\Controller\FileManagerController'   => __DIR__ . '/src/UthandoFileManager/Controller/FileManagerController.php',
    'UthandoFileManager\Controller\UploaderController'      => __DIR__ . '/src/UthandoFileManager/Controller/UploaderController.php',
    'UthandoFileManager\Form\Image'                         => __DIR__ . '/src/UthandoFileManager/Form/Image.php',
    'UthandoFileManager\Hydrator\Image'                     => __DIR__ . '/src/UthandoFileManager/Hydrator/Image.php',
    'UthandoFileManager\InputFilter\Image'                  => __DIR__ . '/src/UthandoFileManager/InputFilter/Image.php',
    'UthandoFileManager\Model\File'                         => __DIR__ . '/src/UthandoFileManager/Model/File.php',
    'UthandoFileManager\Model\Image'                        => __DIR__ . '/src/UthandoFileManager/Model/Image.php',
    'UthandoFileManager\Options\FileManagerOptions'         => __DIR__ . '/src/UthandoFileManager/Options/FileManagerOptions.php',
    'UthandoFileManager\Service\Factory\FileManagerOptions' => __DIR__ . '/src/UthandoFileManager/Service/Factory/FileManagerOptions.php',
    'UthandoFileManager\Service\ImageUploader'              => __DIR__ . '/src/UthandoFileManager/Service/ImageUploader.php',
    'UthandoFileManager\Service\Uploader'                   => __DIR__ . '/src/UthandoFileManager/Service/Uploader.php',
    'UthandoFileManager\UthandoFileManagerException'        => __DIR__ . '/src/UthandoFileManager/UthandoFileManagerException.php',
    'UthandoFileManager\Validator\IsImage'                  => __DIR__ . '/src/UthandoFileManager/Validator/IsImage.php',
    'UthandoFileManager\Validator\MimeType'                 => __DIR__ . '/src/UthandoFileManager/Validator/MimeType.php',
    'UthandoFileManager\View\File'                          => __DIR__ . '/src/UthandoFileManager/View/File.php',
);
