<?php
// Generated by ZF2's ./bin/templatemap_generator.php
return array(
    'uthando-file-manager/asset-manager/delete-file'   => __DIR__ . '/view/uthando-file-manager/asset-manager/delete-file.phtml',
    'uthando-file-manager/asset-manager/delete-folder' => __DIR__ . '/view/uthando-file-manager/asset-manager/delete-folder.phtml',
    'uthando-file-manager/asset-manager/file-tree'     => __DIR__ . '/view/uthando-file-manager/asset-manager/file-tree.phtml',
    'uthando-file-manager/asset-manager/index'         => __DIR__ . '/view/uthando-file-manager/asset-manager/index.phtml',
    'uthando-file-manager/asset-manager/new-folder'    => __DIR__ . '/view/uthando-file-manager/asset-manager/new-folder.phtml',
    'uthando-file-manager/asset-manager/save-image'    => __DIR__ . '/view/uthando-file-manager/asset-manager/save-image.phtml',
    'uthando-file-manager/asset-manager/upload'        => __DIR__ . '/view/uthando-file-manager/asset-manager/upload.phtml',
    'uthando-file-manager/file-manager/index'          => __DIR__ . '/view/uthando-file-manager/file-manager/index.phtml',
    'uthando-file-manager/layout/asset-manager'        => __DIR__ . '/view/uthando-file-manager/layout/asset-manager.phtml',
    'uthando-file-manager/settings/index'              => __DIR__ . '/view/uthando-file-manager/settings/index.phtml',
    'uthando-file-manager/uploader/upload-form'        => __DIR__ . '/view/uthando-file-manager/uploader/upload-form.phtml',
);
