<?php

define("WEBSITEROOT_LOCALPATH", $_SERVER['DOCUMENT_ROOT']);
define("UPLOAD_FILE_TYPES", "jpg|jpeg|gif|png|txt|pdf|zip");

$root=WEBSITEROOT_LOCALPATH;
$newfolder = $root . $_POST["folder"];

function remfolder($dir) {

    if(!file_exists($dir)) return true;

    $cnt = glob($dir . "/" . "*");

    foreach ($cnt as $f) {
        if(is_file($f)) {
            unlink($f);
        }

        if(is_dir($f)) {
            remfolder($f);
        }
    }

    return rmdir($dir);

}

if(file_exists ($newfolder)) {
    //delete the folder
    remfolder($newfolder);
} else {
    //do nothing
}

?>