
<form id="form1">
    <input id="active_folder" name="folder"  type="hidden" />

    <div id="topPanel" style="display:block;position:fixed;top:0px;left:0px;width:100%;padding:15px;background:#fcfcfc;border-bottom:#f7f7f7 1px solid;border-right:#f7f7f7 1px solid">

        <div style="margin-top:5px;margin-bottom:5px;">
            <a id="lnkNewFolder" href="javascript:panelFolder()" style="margin-right:10px;font-size:10px;color:#000;">NEW FOLDER</a>
            <a id="lnkUpload" href="javascript:upload()" style="margin-right:10px;font-size:10px;color:#000;">UPLOAD</a>
        </div>

        <div id="divPreview" style="margin-top:15px;padding:15px;padding-bottom:14px;border:#f3f3f3 1px solid;background:#fefefe;">
            <div style="font-weight:bold;font-size:12pt;margin-bottom:5px;">Folder: <span id="folder_id">/</span> &nbsp; <a href="javascript:refresh()" style="margin-right:10px;font-size:10px;color:#000;font-weight:normal;">REFRESH</a></div>
            <div id="preview_id"></div>
            <a href="#" style="float:right;margin-right:2px;" onclick="$('#divPreview').slideToggle(750, 'easeOutBounce');">close</a>
        </div>

        <div id="divUpload" style="margin-top:15px;padding:15px;border:#f3f3f3 1px solid;background:#fefefe;">
            <iframe id="frmUpload" border="0" style="border:none;height:55px;width:90%" src="about:blank"></iframe>
        </div>

        <div id="divNewFolder" style="margin-top:15px;padding:15px;height:65px;border:#f3f3f3 1px solid;background:#fefefe;">
            <h3 style="margin-top:0px">New Folder</h3>
            <input type="text" id="inpFolder" style="width:120px;height:26px;float:left" value="">
            <input type="button" id="btnAddFolder" value=" create " onclick="createFolder()" class="inpBtn" style="width:70px;height:30px;margin-right:0px" onmouseover="this.className='inpBtnOver';" onmouseout="this.className='inpBtnOut'">
        </div>

    </div>

    <div id="container_id" style="padding:15px;margin-top:45px;">
    </div>
</form>
<script>
    var sid = '<?=$this->sid;?>';
</script>