<?php

define("WEBSITEROOT_LOCALPATH", $_SERVER['DOCUMENT_ROOT']);
define("UPLOAD_FILE_TYPES", "jpg|jpeg|gif|png|txt|pdf|zip");

$root=WEBSITEROOT_LOCALPATH;
$newfolder = $root . $_POST["folder"];

$parent = dirname($newfolder);

if(!is_writable($parent)) {
    echo "Write permission required";
    exit();
}

if(!file_exists ($newfolder)) {
    //create the folder
    mkdir($newfolder);
} else {
    echo "Folder already exists.";
}
?>