<?=$this->headLink()->appendStylesheet($this->basePath('el-finder/css/elfinder.full.css'));?>
<script>
    $(function () {
        var $window = $(window);
        var init_win_height = $window.height() - 400;

        var thisElFinder = $('#elfinder').elfinder({
            // lang: 'ru',             // language (OPTIONAL)
            url: '<?= $this->url('admin/file-manager/connector')?>',  // connector URL (REQUIRED)
            getFileCallback: function (fileInfo) {
                console.log(fileInfo);
                //window.opener.elFinderFileSelected(fileInfo['url']);
                //window.close();
            },
            resizable: false,
            height: init_win_height,
            soundPath : '<?=$this->basePath('el-finder/sounds/');?>'
        });

        var elf = thisElFinder.elfinder('instance');

        var $window = $(window);
        $window.resize(function () {
            var win_height = $window.height() - 400;
            if (thisElFinder.height() != win_height) {
                thisElFinder.height(win_height).resize();
            }
        });
    });
</script>